import { Subject } from './types'

export const SUBJECTS: Record<string, Subject> = {
  Space: {
    emoji: '🚀',
    label: 'Space',
    color: '#7C3AED',
    bg: 'bg-violet-50',
    border: 'border-violet-200',
    video: 'libKVRa01L8',
    facts: [
      { emoji: '🚀', text: 'Space has no air — astronauts must bring oxygen with them!' },
      { emoji: '☀️', text: 'The Sun is so big that one million Earths could fit inside it.' },
      { emoji: '🌙', text: 'The Moon has mountains taller than Mount Everest!' },
      { emoji: '🪐', text: 'Saturn has beautiful rings made of ice and rock.' },
      { emoji: '🌟', text: 'Stars are actually giant balls of burning gas, just like our Sun.' },
    ],
    quiz: [
      { q: 'Which planet is red?', options: ['Venus', 'Mars', 'Saturn'], correct: 1 },
      { q: 'How many planets are in our Solar System?', options: ['7', '8', '9'], correct: 1 },
      { q: 'What is the closest star to Earth?', options: ['The Moon', 'The Sun', 'Jupiter'], correct: 1 },
      { q: 'Which planet has the most moons?', options: ['Earth', 'Saturn', 'Mars'], correct: 1 },
      { q: 'How long does light from the Sun take to reach Earth?', options: ['8 minutes', '8 hours', '8 days'], correct: 0 },
    ],
    typeChallenge: [
      { q: 'How many planets are in our Solar System?', answer: '8', acceptedAnswers: ['eight', '8'] },
      { q: 'What planet is closest to the Sun?', answer: 'mercury', acceptedAnswers: ['mercury'] },
      { q: 'How many moons does Earth have?', answer: '1', acceptedAnswers: ['one', '1', '1 moon'] },
    ],
  },
  Animals: {
    emoji: '🦁',
    label: 'Animals',
    color: '#059669',
    bg: 'bg-emerald-50',
    border: 'border-emerald-200',
    video: 'eUunYTYia3I',
    facts: [
      { emoji: '🐘', text: "Elephants can't jump! They are the only mammal that can't." },
      { emoji: '🐙', text: 'Octopuses have 3 hearts and blue blood!' },
      { emoji: '🦒', text: 'Giraffes have the same number of neck bones as humans — just much bigger!' },
      { emoji: '🦋', text: 'Butterflies taste with their feet.' },
      { emoji: '🐬', text: 'Dolphins sleep with one eye open to stay alert for danger.' },
    ],
    quiz: [
      { q: 'Which is the tallest animal on Earth?', options: ['Lion', 'Elephant', 'Giraffe'], correct: 2 },
      { q: 'How many hearts does an octopus have?', options: ['1', '2', '3'], correct: 2 },
      { q: 'What do butterflies taste with?', options: ['Their tongues', 'Their feet', 'Their eyes'], correct: 1 },
      { q: 'How many legs does an octopus have?', options: ['6', '8', '10'], correct: 1 },
      { q: 'Which animal sleeps the most?', options: ['Lion', 'Koala', 'Dolphin'], correct: 1 },
    ],
    typeChallenge: [
      { q: 'How many hearts does an octopus have?', answer: '3', acceptedAnswers: ['three', '3'] },
      { q: 'What is the tallest animal?', answer: 'giraffe', acceptedAnswers: ['giraffe'] },
      { q: 'How many legs does a spider have?', answer: '8', acceptedAnswers: ['eight', '8'] },
    ],
  },
  Dinosaurs: {
    emoji: '🦕',
    label: 'Dinosaurs',
    color: '#EA580C',
    bg: 'bg-orange-50',
    border: 'border-orange-200',
    video: 'ayKCzl5xRh4',
    facts: [
      { emoji: '🦷', text: 'T-Rex had teeth as long as bananas — and they kept growing back!' },
      { emoji: '🪶', text: 'Some dinosaurs actually had feathers, just like birds today.' },
      { emoji: '🦴', text: 'The word "fossil" comes from a Latin word meaning "dug up".' },
      { emoji: '🌍', text: 'Dinosaurs lived on Earth for about 165 million years!' },
      { emoji: '🐦', text: 'Birds are actually living dinosaurs — they evolved from them.' },
    ],
    quiz: [
      { q: 'Was T-Rex a meat eater?', options: ['Yes', 'No', 'Only plants'], correct: 0 },
      { q: 'What do birds have in common with dinosaurs?', options: ["They're related!", 'Same color', 'Same size'], correct: 0 },
      { q: 'How long did dinosaurs live on Earth?', options: ['1000 years', '10 million years', '165 million years'], correct: 2 },
      { q: 'Which was bigger?', options: ['T-Rex', 'Triceratops', 'Velociraptor'], correct: 0 },
      { q: 'What killed the dinosaurs?', options: ['Ice age', 'Asteroid', 'Flood'], correct: 1 },
    ],
    typeChallenge: [
      { q: 'How long did dinosaurs live on Earth (in millions of years)?', answer: '165', acceptedAnswers: ['165', '165 million', '165 million years'] },
      { q: 'What do scientists dig up to learn about dinosaurs?', answer: 'fossils', acceptedAnswers: ['fossils', 'fossil'] },
      { q: 'Are birds related to dinosaurs?', answer: 'yes', acceptedAnswers: ['yes', 'yeah', 'y'] },
    ],
  },
  Science: {
    emoji: '🧪',
    label: 'Science',
    color: '#2563EB',
    bg: 'bg-blue-50',
    border: 'border-blue-200',
    video: 'lv6dC0coQeI',
    facts: [
      { emoji: '🌈', text: 'A rainbow has 7 colors: Red, Orange, Yellow, Green, Blue, Indigo, Violet.' },
      { emoji: '🧲', text: 'Magnets have two poles — opposite poles attract, same poles repel!' },
      { emoji: '💧', text: 'Water can be a solid (ice), liquid (water), or gas (steam).' },
      { emoji: '🌱', text: "Plants make their own food using sunlight — it's called photosynthesis." },
      { emoji: '⚡', text: 'Lightning is hotter than the surface of the Sun!' },
    ],
    quiz: [
      { q: 'What color is a rainbow?', options: ['Just Blue', 'Many Colors', 'Only Green'], correct: 1 },
      { q: 'What process do plants use to make food?', options: ['Digestion', 'Photosynthesis', 'Evaporation'], correct: 1 },
      { q: 'What are the 3 states of water?', options: ['Hot, Warm, Cold', 'Solid, Liquid, Gas', 'Ice, Snow, Rain'], correct: 1 },
      { q: 'What gas do plants absorb?', options: ['Oxygen', 'CO2', 'Nitrogen'], correct: 1 },
      { q: 'What is the boiling point of water?', options: ['50 degrees', '100 degrees', '200 degrees'], correct: 1 },
    ],
    typeChallenge: [
      { q: 'How many colors are in a rainbow?', answer: '7', acceptedAnswers: ['seven', '7'] },
      { q: 'What is water made of?', answer: 'hydrogen and oxygen', acceptedAnswers: ['hydrogen and oxygen', 'h2o', 'hydrogen oxygen'] },
      { q: 'What pulls things to the ground?', answer: 'gravity', acceptedAnswers: ['gravity'] },
    ],
  },
  Ocean: {
    emoji: '🐋',
    label: 'Ocean',
    color: '#0D9488',
    bg: 'bg-teal-50',
    border: 'border-teal-200',
    video: 'GegMYU4MaAQ',
    facts: [
      { emoji: '🌊', text: "The ocean covers more than 70% of Earth's surface!" },
      { emoji: '🐳', text: 'Blue whales are the largest animals that have ever lived on Earth.' },
      { emoji: '🦈', text: 'Sharks have been around for over 400 million years — older than dinosaurs!' },
      { emoji: '🪸', text: 'Coral reefs are home to 25% of all ocean life.' },
      { emoji: '🦑', text: 'The giant squid has eyes as big as dinner plates!' },
    ],
    quiz: [
      { q: 'What percentage of Earth is covered by ocean?', options: ['30%', '50%', '70%'], correct: 2 },
      { q: 'Which is the largest animal to ever live?', options: ['Elephant', 'Blue Whale', 'Dinosaur'], correct: 1 },
      { q: 'How long have sharks been on Earth?', options: ['10,000 years', '10 million years', '400 million years'], correct: 2 },
      { q: 'How deep is the Mariana Trench?', options: ['1 km', '11 km', '100 km'], correct: 1 },
      { q: 'Which ocean animal sprays ink?', options: ['Shark', 'Octopus', 'Jellyfish'], correct: 1 },
    ],
    typeChallenge: [
      { q: 'What percentage of Earth is covered by ocean?', answer: '70%', acceptedAnswers: ['70%', '70', '70 percent'] },
      { q: 'What is the largest ocean?', answer: 'pacific', acceptedAnswers: ['pacific', 'pacific ocean'] },
      { q: 'How long have sharks been around (in millions of years)?', answer: '400', acceptedAnswers: ['400', '400 million', '400 million years'] },
    ],
  },
  Robots: {
    emoji: '🤖',
    label: 'Robots',
    color: '#DB2777',
    bg: 'bg-pink-50',
    border: 'border-pink-200',
    video: 'mdNMbYbJEAs',
    facts: [
      { emoji: '🤖', text: 'The word "robot" comes from a Czech word meaning "forced labor".' },
      { emoji: '🚀', text: 'NASA has sent robots called Rovers to explore Mars!' },
      { emoji: '🏥', text: 'Robots help doctors perform surgeries — they can be incredibly precise.' },
      { emoji: '🧠', text: "Some robots can learn and get smarter over time — that's AI!" },
      { emoji: '🏭', text: 'Over 3 million robots work in factories around the world.' },
    ],
    quiz: [
      { q: 'What are the NASA robots on Mars called?', options: ['Robots', 'Rovers', 'Walkers'], correct: 1 },
      { q: 'What does AI stand for?', options: ['Animal Intelligence', 'Artificial Intelligence', 'Auto Internet'], correct: 1 },
      { q: 'Can robots help doctors?', options: ['Yes!', 'No', 'Only in movies'], correct: 0 },
      { q: 'Which country has the most robots?', options: ['USA', 'China', 'Japan'], correct: 1 },
      { q: "What does AI help robots do?", options: ['Run faster', 'Think and learn', 'Sleep'], correct: 1 },
    ],
    typeChallenge: [
      { q: 'What does AI stand for?', answer: 'artificial intelligence', acceptedAnswers: ['artificial intelligence', 'ai'] },
      { q: 'What are NASA robots on Mars called?', answer: 'rovers', acceptedAnswers: ['rovers', 'rover'] },
      { q: 'How many robots work in factories?', answer: '3 million', acceptedAnswers: ['3 million', '3000000', '3,000,000'] },
    ],
  },
  Maths: {
    emoji: '🔢',
    label: 'Maths',
    color: '#F59E0B',
    bg: 'bg-amber-50',
    border: 'border-amber-200',
    video: 'jSL5WNcTtUs',
    facts: [
      { emoji: '🔢', text: 'Zero is the only number that is neither positive nor negative!' },
      { emoji: '➕', text: 'The equals sign (=) was invented in 1557 by a Welsh mathematician.' },
      { emoji: '🕐', text: 'A clock face is a circle — 360 degrees split into 12 hours of 30 degrees each!' },
      { emoji: '🧮', text: 'The word "hundred" comes from Old Norse "hundrath", which actually means 120!' },
      { emoji: '📐', text: 'A triangle always has exactly 3 sides and 3 angles — they add up to 180!' },
    ],
    quiz: [
      { q: 'What is 7 x 8?', options: ['54', '56', '58'], correct: 1 },
      { q: 'How many sides does a triangle have?', options: ['2', '3', '4'], correct: 1 },
      { q: 'What is half of 100?', options: ['25', '50', '75'], correct: 1 },
      { q: 'What is 12 x 12?', options: ['124', '144', '164'], correct: 1 },
      { q: 'How many degrees in a right angle?', options: ['45', '90', '180'], correct: 1 },
    ],
    typeChallenge: [
      { q: 'What is 6 x 7?', answer: '42', acceptedAnswers: ['42', 'forty two', 'forty-two'] },
      { q: 'How many sides does a hexagon have?', answer: '6', acceptedAnswers: ['six', '6'] },
      { q: 'What is 100 divided by 4?', answer: '25', acceptedAnswers: ['25', 'twenty five', 'twenty-five'] },
    ],
  },
  English: {
    emoji: '📖',
    label: 'English',
    color: '#7C3AED',
    bg: 'bg-violet-50',
    border: 'border-violet-200',
    video: '8irSFvoyLHQ',
    facts: [
      { emoji: '📚', text: 'English has about 170,000 words currently in use — and new ones are added every year!' },
      { emoji: '🔤', text: 'The most common letter in English is "E"!' },
      { emoji: '📖', text: 'The longest word in English has 189,819 letters — it is the name of a protein!' },
      { emoji: '✏️', text: 'Silent letters like the "k" in "knight" used to be pronounced long ago!' },
      { emoji: '📝', text: 'A sentence that uses every letter of the alphabet is called a pangram — like "The quick brown fox jumps over the lazy dog"!' },
    ],
    quiz: [
      { q: 'Which is a noun?', options: ['Run', 'Beautiful', 'Cat'], correct: 2 },
      { q: 'What is the opposite of "hot"?', options: ['Warm', 'Cold', 'Wet'], correct: 1 },
      { q: 'How many vowels are in the alphabet?', options: ['3', '5', '7'], correct: 1 },
      { q: 'Which word is a verb?', options: ['Happy', 'Jump', 'Blue'], correct: 1 },
      { q: 'What punctuation ends a question?', options: ['.', '!', '?'], correct: 2 },
    ],
    typeChallenge: [
      { q: 'What is the plural of "child"?', answer: 'children', acceptedAnswers: ['children'] },
      { q: 'Name a vowel.', answer: 'a', acceptedAnswers: ['a', 'e', 'i', 'o', 'u', 'aeiou'] },
      { q: 'What is the opposite of "big"?', answer: 'small', acceptedAnswers: ['small', 'little', 'tiny'] },
    ],
  },
  Programming: {
    emoji: '💻',
    label: 'Programming',
    color: '#10B981',
    bg: 'bg-emerald-50',
    border: 'border-emerald-200',
    video: 'iGQRj5V5TVc',
    facts: [
      { emoji: '💻', text: 'The first computer bug was an actual bug — a moth found stuck in a machine!' },
      { emoji: '🎮', text: 'The first video game was made in 1958 — it was like digital tennis!' },
      { emoji: '🌐', text: 'The first website ever made is still online at info.cern.ch!' },
      { emoji: '🤖', text: 'Python is named after "Monty Python", not the snake!' },
      { emoji: '📱', text: 'There are over 7 billion smartphones in the world — more than people with toothbrushes!' },
    ],
    quiz: [
      { q: 'What does "HTML" stand for?', options: ['Hyper Text Markup Language', 'Home Tool Management Language', 'High Tech Modern Language'], correct: 0 },
      { q: 'Which language looks like a snake?', options: ['Java', 'Python', 'C++'], correct: 1 },
      { q: 'What does a programmer write?', options: ['Stories', 'Code', 'Songs'], correct: 1 },
      { q: 'What is a "bug" in coding?', options: ['An insect', 'An error', 'A feature'], correct: 1 },
      { q: 'What shape is a pixel on screen?', options: ['Circle', 'Triangle', 'Square'], correct: 2 },
    ],
    typeChallenge: [
      { q: 'What does "HTML" stand for?', answer: 'hyper text markup language', acceptedAnswers: ['hyper text markup language', 'html'] },
      { q: 'What do programmers call their mistakes?', answer: 'bugs', acceptedAnswers: ['bugs', 'bug', 'errors'] },
      { q: 'What language looks like a snake?', answer: 'python', acceptedAnswers: ['python'] },
    ],
  },
}

export type SubjectRecommendation = {
  videoId: string
  title: string
}

export const SUBJECT_RECOMMENDATIONS: Record<string, SubjectRecommendation[]> = {
  Space: [
    { videoId: 'libKVRa01L8', title: 'Solar System 101 — National Geographic' },
    { videoId: 'LIBf222g0eY', title: 'The Scale of the Universe' },
    { videoId: 'eC2Y7wAJhN8', title: 'Planet Facts for Kids' },
  ],
  Animals: [
    { videoId: 'eUunYTYia3I', title: 'Amazing Animals — Nat Geo Kids' },
    { videoId: 'Xh1BMR7qXzY', title: 'Top 10 Animals for Kids' },
    { videoId: '3APW2vqKN7Y', title: 'Jungle Animals for Children' },
  ],
  Dinosaurs: [
    { videoId: 'ayKCzl5xRh4', title: 'Tyrannosaurus Rex — Pinkfong' },
    { videoId: 'wbJMICL0hEo', title: 'Dinosaur Songs for Kids' },
    { videoId: 'QkIJtS3GmVY', title: 'All About Dinosaurs' },
  ],
  Science: [
    { videoId: 'lv6dC0coQeI', title: 'Earth Science for Kids' },
    { videoId: 'Ki0aYVKnY_w', title: 'Science Experiments for Kids' },
    { videoId: 'PQ8jyG4y2Ew', title: 'The Water Cycle for Kids' },
  ],
  Ocean: [
    { videoId: 'GegMYU4MaAQ', title: 'Sea Animals for Kids' },
    { videoId: '5zMFoVhWRc8', title: 'Deep Ocean Creatures' },
    { videoId: '2bLF8fK9Jmk', title: 'Coral Reef Explained' },
  ],
  Robots: [
    { videoId: 'mdNMbYbJEAs', title: 'Blippi Meets a Robot' },
    { videoId: 'RkEwemWx1_0', title: 'How Robots Are Made' },
    { videoId: 'F_0FypwMXPA', title: 'Cool Robots for Kids' },
  ],
  Maths: [
    { videoId: 'jSL5WNcTtUs', title: 'Numberblocks — Math for Kids' },
    { videoId: 'NybHckSEQBI', title: 'Learn to Count' },
    { videoId: 'G7m1P2VfnKY', title: 'Shapes for Kids' },
  ],
  English: [
    { videoId: '8irSFvoyLHQ', title: 'Learn English for Kids — Dialogues' },
    { videoId: 'Ahc7LVWfmEw', title: 'ABC Song — Alphabet Phonics' },
    { videoId: 'PqobLZ7pblk', title: 'Sight Words for Beginners' },
  ],
  Programming: [
    { videoId: 'iGQRj5V5TVc', title: 'What Is Programming? — Block Coding' },
    { videoId: '4VwE2gb6XKI', title: 'Learn to Code for Kids' },
    { videoId: 'kqtD5dpn9C8', title: 'Scratch Programming Tutorial' },
  ],
}

export const SUBJECT_KEYS = Object.keys(SUBJECTS)
